stages:
  - build
  - deploy
#  - test

docfx:
    image: mono:latest
    stage: build
    before_script:
        - apt update
        - apt install -y unzip wget
        - wget https://github.com/dotnet/docfx/releases/download/v2.59.2/docfx.zip
        - unzip docfx.zip -d docfx
    script:
        - cd docs
        - mono ../docfx/docfx.exe docfx.json build
    artifacts:
        paths:
            - docs/_site
        expire_in: 1 week
    tags:
        - docker

deploy-documentation:
    image: alpine:latest
    stage: deploy
    before_script:
        - apk update
        - apk add rsync
    script:
        - rsync -a docs/_site/ /lectures/viavr-docs/editor/
    tags:
        - docker
        - lectures
    only:
        - master

backend:
   image: node:latest
   stage: build
   cache:
     paths:
       - node_modules
   before_script:
     - node -v
     - npm -v
     - npm i yarn
     - yarn -v
     - npm i
   script:
     - npm run build:backend
   tags:
     - docker

frontend:
   image: node:latest
   stage: build
   cache:
     paths:
       - node_modules
   before_script:
     - node -v
     - npm -v
     - npm i yarn
     - yarn -v
     - npm i
   script:
     - npm run build:frontend
   tags:
     - docker

#package-win:
#  image: electronuserland/builder:wine
#  stage: build
#  cache:
#    paths:
#      - node_modules
#  before_script:
#    - node -v
#    - npm -v
#    - npm i yarn
#    - yarn -v
#    - npm i
#  script:
#    - npm run package:win
#  artifacts:
#    paths:
#      - out/
#    expire_in: 1 week
#  tags:
#    - docker

#package-linux:
#  image: node:latest
#  stage: build
#  cache:
#    paths:
#      - node_modules
#  before_script:
#    - node -v
#    - npm -v
#    - npm i yarn
#    - yarn -v
#    - npm i
#  script:
#    - npm run package:linux
#  artifacts:
#    paths:
#      - out/
#    expire_in: 1 week
#  tags:
#    - docker

#package-mac:
#  image: node:latest
#  stage: build
#  cache:
#    paths:
#      - node_modules
#  before_script:
#    - node -v
#    - npm -v
#    - npm i yarn
#    - yarn -v
#    - npm i
#  script:
#    - npm run package:mac
#  artifacts:
#    paths:
#      - out/
#    expire_in: 1 week
#  tags:
#    - docker

#test:
#  image: electronuserland/builder:wine
#  stage: test
#  # cache:
#  #   paths:
#  #     - node_modules
#  #     - plugins
#  before_script:
#    - node -v
#    - npm -v
#    - npm i yarn
#    - yarn -v
#    - npm i
#  script:
#    # - npm start
#    - npm run test
#    # - mocha --reporter mocha-junit-reporter --reporter-options mochaFIle=junit.xml
##  artifacts:
##    when: always
##    reports:
##      junit:
##        - junit.xml
#  tags:
#    - docker
